### PR TITLE
Fixed issue #9

### PR DESCRIPTION
**Pull request by DmitriySelischev**
Fixed issue #9 Monkey-patch typo that removes TitleIndex get_urls method permanently.

### CODE REVIEW

**Comment by yakky** [comment]
@DmitriySelischev after the merge of #11 could you rebase on top of it to fix the spurious py 3.4 test errors?

**Comment by DmitriySelischev** [comment]
@yakky yep, I will do it

**Comment by yakky** [comment]
@DmitriySelischev thanks, PR merged

**Comment by DmitriySelischev** [comment]
@yakky I think that I accidentally rebased **under** your PR #11. Is it ok?

**Pull request merged**
